# Generated by Django 3.0.6 on 2020-05-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
