# Generated by Django 3.0.6 on 2020-05-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvjson',
            name='json',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
