# Generated by Django 3.0.6 on 2020-05-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cvjson_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvjson',
            name='json',
            field=models.CharField(max_length=10000),
        ),
    ]
